### PR TITLE
fix: hide schedules that are live from /games

### LINKED ISSUE #67: Don't show the live game in the games panel or display it as LIVE since it is completely empty otherwise.

### PR DESCRIPTION
**Pull request by samdharris**
### Overview

Resolves #67 by filtering the active games list, removing any games that are currently in the active state. This will stop poorly rendered games from showing up since not enough information is provided to display anything meaningful.

### CODE REVIEW

File: pages/games.vue [hunk 1]
```diff
@@ -70,8 +70,13 @@ export default {
             async handler(newSeason) {
                 this.season = Number(newSeason) || 3;
 
-                this.games = await Http.for('games/season').get(this.season);
+                const games = await Http.for('games/season').get(this.season);
```
Comment (stephen-slm) [inline pages/games.vue]: @samdharris Do you think you could change this request to use the axios object instead of the HTTP? We are moving away from the HTTP objective as and when we work on a area, just switch it over?

You should be able to find other examples in the project, something like `this.$axios.get(url)`?

**Review by stephen-slm — CHANGES_REQUESTED** [review]

**Comment by stephen-slm** [comment]
@samdharris Have you used asyncData before? This looks like it could be a god place to get the games on the server prior to serving the page (ping me on discord if not, we could find a good example and see if its a good place to put it).

File: pages/games.vue (hunk 1 above)
Comment (samdharris) [reply pages/games.vue]: @MambaDev job done

**Review by stephen-slm — CHANGES_REQUESTED** [review]
You just need to ensure to correct your commit message styles, this could be done by amending or squashing to a single commit.
